name: Build & Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-and-test:
    uses: karmakrafts/workflows/.github/workflows/cpp-17-20.yml@master
    